DROP TABLE IF EXISTS Visits;
CREATE TABLE IF NOT EXISTS Visits (
    slug TEXT PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO Visits (slug, count) VALUES ('/', 0);
