name: Run Tests

on:
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *" # every day at midnight UTC

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  # Install a specific version of uv.
                  version: "0.7.8"

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: "tests/.python-version"

            - name: Install the project
              working-directory: tests
              run: uv sync --locked --all-extras --dev

            - name: Run tests
              working-directory: tests
              run: uv run pytest
